In [1]:
# Force the local gqcpy to be imported
import sys
sys.path.insert(0, '../../build/gqcpy/')

import gqcpy
import numpy as np

# Preliminary functions
Functions that make our life easier, since we will be reusing some code.

In [2]:
def dimensions(molecule):
    """
    Return the dimensions (N, M) of a molecule in a given basis. Here, N is the number of electrons and M the number of spinors.
    """
    N = molecule.numberOfElectrons()

    spin_orbital_basis = gqcpy.USpinOrbitalBasis_d(molecule, "STO-3G")
    M = spin_orbital_basis.numberOfSpinors()
    
    return (N, M)

In [3]:
def onv_bases(N, K, transition = "detachment"):
    """
    Create two ONV bases, based on whether we are describing an electron attachment or detachment.
    """

    N_alpha = N//2 + 1 if N%2 else N//2
    N_beta = N//2
    
    if transition == "detachment":
        onv_basis_I = gqcpy.SpinResolvedONVBasis(K, N_alpha, N_beta - 1)  # number of spatial orbitals, number of alpha-electrons, number of beta-electrons
        onv_basis_J = gqcpy.SpinResolvedONVBasis(K, N_alpha, N_beta)  # number of spatial orbitals, number of alpha-electrons, number of beta-electrons
        
    elif transition == "attachment":
        onv_basis_I = gqcpy.SpinResolvedONVBasis(K, N_alpha + 1, N_beta)  # number of spatial orbitals, number of alpha-electrons, number of beta-electrons
        onv_basis_J = gqcpy.SpinResolvedONVBasis(K, N_alpha, N_beta)  # number of spatial orbitals, number of alpha-electrons, number of beta-electrons
        
    else:
        print("Specify a valid electron transition process: attachment/detachment.")
        return None
    
    return (onv_basis_I, onv_basis_J)

In [4]:
def C_RHF(molecule):
    
    N = molecule.numberOfElectrons()
    N_P = molecule.numberOfElectronPairs()
    
    spin_orbital_basis = gqcpy.RSpinOrbitalBasis_d(molecule, "STO-3G")
    K = spin_orbital_basis.numberOfSpatialOrbitals()
    #print("N: {}\nN_P: {}\nK: {}".format(N, N_P, K))

    hamiltonian = gqcpy.RSQHamiltonian.Molecular(spin_orbital_basis, molecule)
    S = spin_orbital_basis.quantizeOverlapOperator().parameters()

    environment = gqcpy.RHFSCFEnvironment.WithCoreGuess(N, hamiltonian, S)
    solver = gqcpy.RHFSCFSolver.Plain()
    objective = gqcpy.DiagonalRHFFockMatrixObjective(hamiltonian)  # use the default threshold of 1.0e-08
    rhf_parameters = gqcpy.RHF.optimize(objective, solver, environment).groundStateParameters()
    
    return rhf_parameters.expansion()

In [5]:
def C_UHF(molecule):
    N = molecule.numberOfElectrons()
    N_alpha = N//2 + 1 if N%2 else N//2
    N_beta = N//2

    spinor_basis = gqcpy.RSpinOrbitalBasis_d(molecule, "STO-3G")
    K = spinor_basis.numberOfSpatialOrbitals()
    #print("N_alpha: {}\nN_beta: {}\nK: {}".format(N_alpha, N_beta, K))
    
    hamiltonian = gqcpy.RSQHamiltonian.Molecular(spinor_basis, molecule) 
    S = spinor_basis.quantizeOverlapOperator().parameters()
    
    environment = gqcpy.UHFSCFEnvironment.WithCoreGuess(N_alpha, N_beta, hamiltonian, S)
    solver = gqcpy.UHFSCFSolver.Plain()
    uhf_parameters = gqcpy.UHF.optimize(solver, environment).groundStateParameters()
    return uhf_parameters.expansion()

In [6]:
def TM(C_ion, C_neutral):
    return C_ion.inverse().transformed(C_neutral)

In [7]:
def uFCI(molecule, onv_basis):
    """
    FCI calculations for an unrestricted spin-orbital basis.
    """
    spin_orbital_basis = gqcpy.USpinOrbitalBasis_d(molecule, "STO-3G") # the underlying scalar AO basis is not orthonormal
    spin_orbital_basis.lowdinOrthonormalize() # after using Löwdin's orthonormalizing procedure, the spin orbital basis is now orthonormal
    
    hamiltonian = gqcpy.USQHamiltonian.Molecular(spin_orbital_basis, molecule)
    
    solver = gqcpy.EigenproblemSolver.Dense()
    environment = gqcpy.CIEnvironment.Dense(hamiltonian, onv_basis)

    ci_parameters = gqcpy.CI(onv_basis).optimize(solver, environment).groundStateParameters()
    
    return ci_parameters

# Molecular set-up

Generate the neutral molecule with N electrons, a positive ion with N-1 electrons (charge +1) and a negative ion with N+1 electrons (charge -1).

In [8]:
neutral_molecule = gqcpy.Molecule.ReadXYZ("../../gqcp/tests/data/h2.xyz" , 0)  # create a neutral molecule with N electrons
positive_ion = gqcpy.Molecule.ReadXYZ("../../gqcp/tests/data/h2.xyz" , +1)  # create a an ion N-1 electrons
negative_ion = gqcpy.Molecule.ReadXYZ("../../gqcp/tests/data/h2.xyz" , -1)  # create a an ion with N+1 electrons

#neutral_molecule = gqcpy.Molecule.ReadXYZ("../../gqcp/tests/data/h2o_crawdad.xyz" , 0)  # create a neutral molecule with N electrons
#positive_ion = gqcpy.Molecule.ReadXYZ("../../gqcp/tests/data/h2o_crawdad.xyz" , +1)  # create a an ion N-1 electrons
#negative_ion = gqcpy.Molecule.ReadXYZ("../../gqcp/tests/data/h2o_crawdad.xyz" , -1)  # create a an ion with N+1 electrons

In [9]:
N, M = dimensions(neutral_molecule)
K = M//2 # number of spinors per spin compound

onv_basis_I, onv_basis_J = onv_bases(N, K, "detachment")

# Fukui matrix in the uncorrelated limit

In [10]:
C_neutral = C_UHF(neutral_molecule)
C_ion = C_UHF(positive_ion)

In [11]:
U = TM(C_ion, C_neutral)

In [12]:
print("Is C_ion unitary? ", C_ion.isUnitary())
print("Is C_neutral unitary? ", C_neutral.isUnitary())
print("Is U unitary? ", U.isUnitary())

Is C_ion unitary?  False
Is C_neutral unitary?  False
Is U unitary?  True


In [13]:
Psi_I = gqcpy.LinearExpansion_SpinResolved.HartreeFock(onv_basis_I)
print(Psi_I.coefficients())
Psi_J = gqcpy.LinearExpansion_SpinResolved.HartreeFock(onv_basis_J)
print(Psi_J.coefficients())

[1. 0.]
[1. 0. 0. 0.]


In [14]:
DM_I = Psi_I.calculateSpinResolved1DM()
DM_J = Psi_J.calculateSpinResolved1DM()

In [15]:
DM_I = DM_I.transformed(U)

fukui_matrix_neg = (DM_J - DM_I).orbitalDensity()
fukui_matrix_neg

array([[ 1.00000000e+00, -8.32667268e-17],
       [-8.32667268e-17, -6.93334780e-33]])

In [16]:
fukui_eigenvalues, fukui_naturals = np.linalg.eigh(fukui_matrix_neg)
print(np.round(fukui_naturals,3))
print(fukui_eigenvalues)

[[-0. -1.]
 [-1.  0.]]
[-1.38666956e-32  1.00000000e+00]


# Fukui matrix when correlation is present

In [17]:
Psi_I = uFCI(positive_ion, onv_basis_I)
print(Psi_I.coefficients())
Psi_J = uFCI(neutral_molecule, onv_basis_J)
print(Psi_J.coefficients())

[-0.70710678 -0.70710678]
[-0.44032588 -0.55327491 -0.55327491 -0.44032588]


In [18]:
DM_I = Psi_I.calculateSpinResolved1DM()
DM_J = Psi_J.calculateSpinResolved1DM()

In [19]:
DM_I = DM_I.transformed(U)

fukui_matrix_neg = (DM_J - DM_I).orbitalDensity()
fukui_matrix_neg

array([[0.5       , 1.47448503],
       [1.47448503, 0.5       ]])

In [20]:
fukui_eigenvalues, fukui_naturals = np.linalg.eigh(fukui_matrix_neg)
print(np.round(fukui_naturals,3))
print(fukui_eigenvalues)

[[ 0.707 -0.707]
 [-0.707 -0.707]]
[-0.97448503  1.97448503]
