In [1]:
# Force the local gqcpy to be imported
import sys
sys.path.insert(0, '../../build/gqcpy/')

import gqcpy
import numpy as np

# Preliminary functions
Functions that make our life easier, since we will be reusing some code.

In [2]:
def dimensions(molecule):
    """
    Return the dimensions (N, M) of a molecule in a given basis. Here, N is the number of electrons and M the number of spinors.
    """
    N = molecule.numberOfElectrons()

    spin_orbital_basis = gqcpy.USpinOrbitalBasis_d(molecule, "STO-3G")
    M = spin_orbital_basis.numberOfSpinors()
    
    return (N, M)

In [3]:
def onv_bases(N, K):
    """
    Create three ONV bases: I for the (N-1) electron system, J for the N-electron system and K for the (N+1)-electron system.
    """

    N_alpha = N//2 + 1 if N%2 else N//2
    N_beta = N//2
    
    onv_basis_I = gqcpy.SpinResolvedONVBasis(K, N_alpha, N_beta - 1)  # number of spatial orbitals, number of alpha-electrons, number of beta-electrons
    onv_basis_J = gqcpy.SpinResolvedONVBasis(K, N_alpha, N_beta)  # number of spatial orbitals, number of alpha-electrons, number of beta-electrons
    onv_basis_K = gqcpy.SpinResolvedONVBasis(K, N_alpha + 1, N_beta)  # number of spatial orbitals, number of alpha-electrons, number of beta-electrons

    return (onv_basis_I, onv_basis_J, onv_basis_K)

In [4]:
def C_RHF(molecule):
    """
    Generate restricted spinors, defined as the expansion coefficients in the scalar AO basis, from a restricted
    Hartree-Fock calculation.
    """
    N = molecule.numberOfElectrons()
    N_P = molecule.numberOfElectronPairs()
    
    spin_orbital_basis = gqcpy.RSpinOrbitalBasis_d(molecule, "STO-3G")
    K = spin_orbital_basis.numberOfSpatialOrbitals()
    #print("N: {}\nN_P: {}\nK: {}".format(N, N_P, K))

    hamiltonian = gqcpy.RSQHamiltonian.Molecular(spin_orbital_basis, molecule)
    S = spin_orbital_basis.quantizeOverlapOperator().parameters()

    environment = gqcpy.RHFSCFEnvironment.WithCoreGuess(N, hamiltonian, S)
    solver = gqcpy.RHFSCFSolver.Plain()
    objective = gqcpy.DiagonalRHFFockMatrixObjective(hamiltonian)  # use the default threshold of 1.0e-08
    rhf_parameters = gqcpy.RHF.optimize(objective, solver, environment).groundStateParameters()
    
    return rhf_parameters.expansion()

In [5]:
def C_UHF(molecule):
    """
    Generate unrestricted spin-orbitals, for each spin component defined as the expansion coefficients 
    in the scalar AO basis, from an unrestricted Hartree-Fock calculation.
    """
    N = molecule.numberOfElectrons()
    N_alpha = N//2 + 1 if N%2 else N//2
    N_beta = N//2

    spinor_basis = gqcpy.RSpinOrbitalBasis_d(molecule, "STO-3G")
    K = spinor_basis.numberOfSpatialOrbitals()
    #print("N_alpha: {}\nN_beta: {}\nK: {}".format(N_alpha, N_beta, K))
    
    hamiltonian = gqcpy.RSQHamiltonian.Molecular(spinor_basis, molecule) 
    S = spinor_basis.quantizeOverlapOperator().parameters()
    
    environment = gqcpy.UHFSCFEnvironment.WithCoreGuess(N_alpha, N_beta, hamiltonian, S)
    solver = gqcpy.UHFSCFSolver.Plain()
    uhf_parameters = gqcpy.UHF.optimize(solver, environment).groundStateParameters()
    return uhf_parameters.expansion()

In [6]:
def TM(C_ion, C_neutral):
    """
    Return a transformation matrix that expresses a neutral spinor/spin-orbital in terms of the ones of the ionized molecule.
    """
    return C_ion.inverse().transformed(C_neutral)

In [7]:
def uFCI(molecule, onv_basis):
    """
    FCI calculations for an unrestricted spin-orbital basis.
    """
    spin_orbital_basis = gqcpy.USpinOrbitalBasis_d(molecule, "STO-3G") # the underlying scalar AO basis is not orthonormal
    spin_orbital_basis.lowdinOrthonormalize() # after using Löwdin's orthonormalizing procedure, the spin orbital basis is now orthonormal
    
    hamiltonian = gqcpy.USQHamiltonian.Molecular(spin_orbital_basis, molecule)
    
    solver = gqcpy.EigenproblemSolver.Dense()
    environment = gqcpy.CIEnvironment.Dense(hamiltonian, onv_basis)

    ci_parameters = gqcpy.CI(onv_basis).optimize(solver, environment).groundStateParameters()
    
    return ci_parameters

# Molecular set-up

Generate the neutral molecule with N electrons, a positive ion with N-1 electrons (charge +1) and a negative ion with N+1 electrons (charge -1).

In [8]:
#neutral_molecule = gqcpy.Molecule.ReadXYZ("../../gqcp/tests/data/h2.xyz" , 0)  # create a neutral molecule with N electrons
#positive_ion = gqcpy.Molecule.ReadXYZ("../../gqcp/tests/data/h2.xyz" , +1)  # create a an ion N-1 electrons
#negative_ion = gqcpy.Molecule.ReadXYZ("../../gqcp/tests/data/h2.xyz" , -1)  # create a an ion with N+1 electrons

neutral_molecule = gqcpy.Molecule.ReadXYZ("../../gqcp/tests/data/h2o_crawdad.xyz" , 0)  # create a neutral molecule with N electrons
positive_ion = gqcpy.Molecule.ReadXYZ("../../gqcp/tests/data/h2o_crawdad.xyz" , +1)  # create a an ion N-1 electrons
negative_ion = gqcpy.Molecule.ReadXYZ("../../gqcp/tests/data/h2o_crawdad.xyz" , -1)  # create a an ion with N+1 electrons

In [9]:
N, M = dimensions(neutral_molecule)
K = M//2 # number of spinors per spin compound

onv_basis_I, onv_basis_J, onv_basis_K = onv_bases(N, K)

# Fukui matrix in the uncorrelated limit

To generate the transformation matrix [$\mathbf{U}^\pm$](https://gqcg-res.github.io/dariatols_knowdes/fukui-matrix.html), we must combine the coefficient matrix of the neutral molecule and the ion. More details on the transformation of the density matrix is found in the link.

In [10]:
C_neutral = C_UHF(neutral_molecule)
C_pos = C_UHF(positive_ion)
C_neg = C_UHF(negative_ion)

U_pos = TM(C_pos, C_neutral)
U_neg = TM(C_neg, C_neutral)

Because unitary transformations preserve the inner product, only $\mathbf{U}$ should be a unitary matrix. 

In [11]:
print("Is C_pos / C_neg unitary? {} / {}".format(C_pos.isUnitary(), C_neg.isUnitary()))
print("Is C_neutral unitary? ", C_neutral.isUnitary())
print("Is U_pos / U_neg unitary? {} / {}".format(U_pos.isUnitary(), U_neg.isUnitary()))

Is C_pos / C_neg unitary? False / False
Is C_neutral unitary?  False
Is U_pos / U_neg unitary? True / True


Build the linear expansion for a CI wave function in the Hartree-Fock formalism, where all coefficients of a given ONV basis are zero except for the HF determinant.

In [17]:
Psi_I = gqcpy.LinearExpansion_SpinResolved.HartreeFock(onv_basis_I)
#print(Psi_I.coefficients())
Psi_J = gqcpy.LinearExpansion_SpinResolved.HartreeFock(onv_basis_J)
#print(Psi_J.coefficients())
Psi_K = gqcpy.LinearExpansion_SpinResolved.HartreeFock(onv_basis_K)
#print(Psi_K.coefficients())

print("ONV basis dimensions:\n---------------------\nN-1:\t{}\nN:\t{}\nN+1:\t{}".format(
        len(Psi_I.coefficients()), len(Psi_J.coefficients()), len(Psi_K.coefficients())))

ONV basis dimensions:
---------------------
N-1:	735
N:	441
N+1:	147


To calculate the Fukui matrix, we will need the difference of two density matrices, expressed in the same spin-orbital basis. Therefore, we must transform the density matrix of the ionary species. The density matrix of the neutral species `DM_J` is already in terms of its own spin-orbitals and must therefore not be transformed.

In [18]:
DM_I = Psi_I.calculateSpinResolved1DM()
DM_J = Psi_J.calculateSpinResolved1DM()
DM_K = Psi_K.calculateSpinResolved1DM()

DM_I = DM_I.transformed(U_pos)
DM_K = DM_K.transformed(U_neg)

Due to the discontinuity in the energy versus the number of electrons, one must define an upper and lower limit of the Fukui function and accordingly split the Fukui matrix into a positive and negative component. Here, `FM_pos` is $F^+_{pq}$ and `FM_neg` is $F^-_{pq}$.

In [27]:
FM_pos = DM_K - DM_J
FM_neg = DM_J - DM_I

To assess the quality of the algebraic manipulations ([Bultinck2011](https://pubs.rsc.org/en/content/articlelanding/2011/CP/c0cp02268c#!divAbstract)), we must check the effect of adding or removing an electron on the Fukui matrix. To obtain the $(N+1)$-electron system, we have added an $\alpha$-electron to its spin-orbitals. This means that the $\alpha$ part of $\mathbf{F}^+$ will incorporate an additional electron, which must be reflected in the trace of the Fukui matrix. 

In [32]:
np.trace(FM_pos.alpha)

1.0000000000000069

Additionally, since `Psi_J` and `Psi_K` both have the same number of $\beta$-electrons, the trace of $\mathbf{F}^{+,\beta}$ should be zero.

In [33]:
np.trace(FM_pos.beta)

2.427616755621559e-15

We can work analogously for $\mathbf{F}^-$: `Psi_I` has one less $\beta$ electron than `Psi_J` and consequently, the trace of $F^{-,\beta}$ should be 1

In [34]:
np.trace(FM_neg.beta)

0.9999999999999963

whereas the trace of $F^{-,\alpha}$ should be zero now.

In [35]:
np.trace(FM_neg.alpha)

-2.5431046157819992e-15

In [20]:
#F_eigenvalues, F_naturals = np.linalg.eigh(FM_neg.orbitalDensity())

#print(fukui_eigenvalues)

In [26]:
np.trace(FM_neg.beta)

0.9999999999999963

### $F^{+}$

First, we will diagonalize $F^{+,\alpha}$ which has trace 1. According to [Bultinck2011](https://pubs.rsc.org/en/content/articlelanding/2011/CP/c0cp02268c#!divAbstract), the Frontier Molecular Orbital (FMO) approximation is perfect if a single eigenvalue equal to 1 appears. Its corresponding Fukui natural should be solely composed of the FMO of the neutral compound. In our case, we have an eigenvalue of 1, with a corresponding Fukui natural that is exclusively constructed of the FMO of the neutral molecule. Other eigenvalues come in pairs, as described in the article.

In [85]:
F_pos_eigenvalues, F_pos_naturals = np.linalg.eigh(FM_pos.alpha)

print(F_pos_eigenvalues)
print("\n\n")
print(np.round(F_pos_naturals, 3))

[-1.32857404e-01  3.74797419e-16  4.33659659e-16  1.39988019e-15
  1.63580995e-15  1.32857404e-01  1.00000000e+00]



[[-0.    -0.997 -0.008 -0.062  0.054  0.    -0.   ]
 [ 0.     0.063 -0.    -0.998  0.009 -0.     0.   ]
 [-0.753 -0.     0.     0.    -0.    -0.658 -0.   ]
 [-0.     0.054 -0.005  0.012  0.998  0.     0.   ]
 [-0.    -0.007  1.    -0.001  0.006  0.    -0.   ]
 [-0.     0.    -0.    -0.     0.     0.    -1.   ]
 [ 0.658 -0.     0.     0.     0.    -0.753 -0.   ]]


Diagonalizing $F^{+,\beta}$ results in eigenvalues that either come in pairs, or are zero.

In [87]:
F_pos_eigenvalues, F_pos_naturals = np.linalg.eigh(FM_pos.beta)

print(F_pos_eigenvalues)
print("\n\n")
print(np.round(F_pos_naturals, 3))

[-8.47147881e-02 -5.32910853e-03 -6.54570832e-16  4.65957588e-20
  1.33891934e-15  5.32910853e-03  8.47147881e-02]



[[-0.005  0.     1.    -0.     0.019 -0.    -0.004]
 [ 0.551 -0.     0.017  0.    -0.664 -0.     0.506]
 [ 0.    -0.709 -0.     0.     0.    -0.705  0.   ]
 [-0.489 -0.     0.01   0.    -0.748 -0.    -0.449]
 [ 0.    -0.    -0.    -1.    -0.    -0.    -0.   ]
 [-0.676  0.     0.    -0.     0.    -0.     0.736]
 [-0.    -0.705  0.     0.     0.     0.709  0.   ]]


### $F^{-}$

Similar to $F^{+}$, we can both diagonalize the $\alpha$ and $\beta$ part of $F^{-}$. $F^{-,\beta}$ with trace 1 will have a Fukui eigenvalue of 1, with a corresponding Fukui natural consisting of the FMO.

In [88]:
F_neg_eigenvalues, F_neg_naturals = np.linalg.eigh(FM_neg.beta)

print(F_neg_eigenvalues)
print("\n\n")
print(np.round(F_neg_naturals, 3))

[-1.18219603e-01 -9.83592966e-02 -8.47515873e-16 -2.93218051e-16
  9.83592966e-02  1.18219603e-01  1.00000000e+00]



[[-0.004  0.     0.089 -0.996  0.     0.004  0.   ]
 [-0.134  0.    -0.976 -0.086  0.     0.151 -0.   ]
 [ 0.     0.671  0.     0.     0.741 -0.     0.   ]
 [ 0.65  -0.    -0.2   -0.024 -0.    -0.732 -0.   ]
 [-0.     0.     0.    -0.     0.    -0.    -1.   ]
 [ 0.748 -0.     0.     0.     0.     0.664 -0.   ]
 [-0.    -0.741 -0.    -0.     0.671 -0.     0.   ]]


In [89]:
F_neg_eigenvalues, F_neg_naturals = np.linalg.eigh(FM_neg.alpha)

print(F_neg_eigenvalues)
print("\n\n")
print(np.round(F_neg_naturals, 3))

[-1.82838831e-01 -1.76256683e-01 -7.39123799e-16 -3.85004198e-16
  2.71846167e-20  1.76256683e-01  1.82838831e-01]



[[ 0.     0.    -0.052 -0.999 -0.    -0.    -0.   ]
 [-0.291 -0.     0.889 -0.046 -0.005  0.     0.35 ]
 [ 0.    -0.642 -0.     0.     0.     0.767 -0.   ]
 [ 0.569  0.     0.454 -0.023 -0.003 -0.    -0.685]
 [ 0.    -0.    -0.006  0.001 -1.     0.    -0.   ]
 [ 0.769  0.    -0.     0.     0.     0.     0.639]
 [-0.     0.767  0.    -0.     0.     0.642 -0.   ]]


# Fukui matrix when correlation is present

In [17]:
Psi_I = uFCI(positive_ion, onv_basis_I)
#print(Psi_I.coefficients())
Psi_J = uFCI(neutral_molecule, onv_basis_J)
#print(Psi_J.coefficients())

In [18]:
DM_I = Psi_I.calculateSpinResolved1DM()
DM_J = Psi_J.calculateSpinResolved1DM()

In [19]:
DM_I = DM_I.transformed(U)

fukui_matrix_neg = (DM_J - DM_I).orbitalDensity()
fukui_matrix_neg

array([[-1.14294316e-04, -1.42345253e-03, -1.18669477e-03,
         7.00084051e-02,  1.59070327e-02, -7.89767262e-02,
        -3.79127022e-02],
       [-1.42345253e-03,  3.79812936e-02, -4.34359557e-03,
        -5.90144899e-01, -1.57454367e-01,  7.30396934e-01,
         3.32711417e-01],
       [-1.18669477e-03, -4.34359557e-03, -5.18485116e-02,
         3.97693239e-02, -4.48641316e-02,  6.92625898e-01,
         3.71937673e-02],
       [ 7.00084051e-02, -5.90144899e-01,  3.97693239e-02,
        -3.57620125e-01,  3.89425290e-02,  1.76182538e-01,
         8.45921117e-01],
       [ 1.59070327e-02, -1.57454367e-01, -4.48641316e-02,
         3.89425290e-02,  1.19461790e+00, -2.39134700e-01,
        -2.50553617e-01],
       [-7.89767262e-02,  7.30396934e-01,  6.92625898e-01,
         1.76182538e-01, -2.39134700e-01,  1.19907183e-01,
         1.68609784e-02],
       [-3.79127022e-02,  3.32711417e-01,  3.71937673e-02,
         8.45921117e-01, -2.50553617e-01,  1.68609784e-02,
         5.7076554

In [20]:
fukui_eigenvalues, fukui_naturals = np.linalg.eigh(fukui_matrix_neg)
print(np.round(fukui_naturals,3))
print(fukui_eigenvalues)

[[ 0.057  0.01   0.994  0.061  0.013  0.051  0.036]
 [-0.495 -0.136  0.106 -0.624 -0.099 -0.456 -0.344]
 [-0.163 -0.629  0.001  0.603  0.223 -0.339 -0.223]
 [-0.627  0.367  0.003  0.132  0.613  0.279 -0.03 ]
 [ 0.05  -0.005 -0.001 -0.134  0.357 -0.521  0.762]
 [ 0.36   0.582  0.003  0.178  0.196 -0.52  -0.437]
 [ 0.448 -0.335 -0.008 -0.42   0.631  0.233 -0.242]]
[-1.52805182e+00 -6.97471559e-01  5.12927886e-05  1.49626364e-01
  7.02979684e-01  8.78279811e-01  1.49458623e+00]
